const ACTIVITY_TYPE_MATCH = 'match'
const ACTIVITY_TYPE_UNMATCH = 'unmatch'
const ACTIVITY_TYPE_PROFILE_VIEW = 'profile-view'
const ACTIVITY_TYPE_CONNECT = 'connect'
const ACTIVITY_TYPE_REPORT = 'report'
const ACTIVITY_TYPE_BLOCK = 'block'

module.exports = {
  ACTIVITY_TYPE_MATCH,
  ACTIVITY_TYPE_UNMATCH,
  ACTIVITY_TYPE_PROFILE_VIEW,
  ACTIVITY_TYPE_CONNECT,
  ACTIVITY_TYPE_REPORT,
  ACTIVITY_TYPE_BLOCK
}
