const EVENT_TYPE_MATCH = 'match'
const EVENT_TYPE_UNMATCH = 'unmatch'
const EVENT_TYPE_MESSAGE = 'message'
const EVENT_TYPE_PROFILE_VIEW = 'profile-view'
const EVENT_TYPE_CONNECT = 'connect'
const EVENT_TYPE_BLOCK = 'block'
const EVENT_TYPE_UNBLOCK = 'unblock'
const EVENT_TYPE_REPORT = 'report'
const EVENT_TYPE_DISCONNECT = 'disconnect'

module.exports = {
  EVENT_TYPE_MATCH,
  EVENT_TYPE_UNMATCH,
  EVENT_TYPE_MESSAGE,
  EVENT_TYPE_PROFILE_VIEW,
  EVENT_TYPE_CONNECT,
  EVENT_TYPE_BLOCK,
  EVENT_TYPE_UNBLOCK,
  EVENT_TYPE_REPORT,
  EVENT_TYPE_DISCONNECT
}
